# Site settings
title: Merchise
pagetitle: Merchise - Boosting the Cuban Startup Scene
email: info@merchise.com
url: https://merchise.com
description: "Merchise"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 08ABF0 #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Merchise
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/merchise
  - title: facebook
    url: http://facebook.com/merchisestartups

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Vedado, Havana 70100

# Credits content
credits: 'Merchise'

# Build settings
markdown: kramdown
permalink: pretty
